services:
  uptime-kuma:
    build:
      context: .
      dockerfile: Dockerfile
    image: agorastis/uptime-kuma
    restart: always
    ports:
      - 3001:3001
    volumes:
      - ./data:/app/data
    container_name: uptime-kuma
volumes:
  uptime-kuma: {}
networks: {}
